import Head from 'next/head'
import Header from '../components/Header'
import TestMap from '../components/TestMap'
export default function Home() {
  
  return (
    <div className='test'>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />
      </Head>
      <Header/>
      <TestMap/>
    </div>
  )
}
