import Head from 'next/head'
import Header from '../components/Header'
import MapAndPanel from '../components/MapAndPanel'
import WeatherDisplay from '../components/WeatherDisplay'
import Map from '../components/MapAndPanel'
import { Container} from '@mui/system'
import { Grid } from '@mui/material'

export default function Home() {
  
  return (
    <Grid container>  
      <Head>
        <title>Weather</title>
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />
        <meta name="description" content="Generated by create next app" />
      </Head>
    <Container><MapAndPanel/></Container>
    </Grid>
      
  )
}
